language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.5
  - nightly

# matrix:
#   allow_failures:
#     - julia: nightly

branches:
  only:
    - master

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

after_success:
  - julia --color=yes --project=test/coverage/ -e 'using Pkg; Pkg.instantiate()'
  - julia --color=yes --project=test/coverage/ test/coverage/coverage.jl

# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.5
#       os: linux
#       script:
#         - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate()'
#         - julia --color=yes --project=docs/ docs/make.jl
#       after_success: skip
